# -*- coding: utf-8 -*-
"""Mental health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1digZY3fdA3oFg6JHLQxfR2-hcSQ57N-l
"""

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Techaxis/Mental Health Dataset.csv")

df

df.shape

df.info()

df.describe()

df.isnull().sum()

df["Country"].value_counts().plot.bar()

import matplotlib.pyplot as plt
df['Gender'].value_counts().plot.pie()

a=df.groupby("Occupation")
a["Gender"].value_counts().plot.bar()

import matplotlib.pyplot as plt
b=df.groupby("Country")
ff=b['Gender'].value_counts().unstack()
ff
# bb=b['Gender'].value_counts().plot.bar()
# bb

aa=b["Mental_Health_History"].value_counts().unstack()
aa

d=pd.concat([aa,ff],axis="columns")
d

df["Mood_Swings"].value_counts()

w=df.groupby("Gender")
w["Mood_Swings"].value_counts().unstack().plot.bar()

w["Changes_Habits"].value_counts().unstack().plot.bar()

w["Work_Interest"].value_counts().unstack().plot.bar()

b["Work_Interest"].value_counts().unstack().plot.bar()

df["Coping_Struggles"].value_counts().plot.pie()

w["Coping_Struggles"].value_counts().plot.bar()

b["Coping_Struggles"].value_counts().unstack()

b["care_options"].value_counts().unstack()

w["care_options"].value_counts().unstack().plot.bar()

w["treatment"].value_counts().plot.bar()

pp=b["Occupation"].apply(lambda x:x.str.contains("Student").sum()).plot.bar()
pp

b["care_options"].value_counts().unstack()

df["Days_Indoors"].value_counts()
w["Days_Indoors"].value_counts().plot.bar()

df["Days_Indoors"].value_counts().plot.bar()

def days(x):
  if x == "1-14 days":
    return "Rarely"
  elif x == "15-30 days":
     return "Offten"
  elif x == "31-60 days":
     return "Mostly"
  elif x == "Go out Every day":
     return "Everyday"
  elif x == "More than 2 months":
     return "More than 2 months"
  else:
     return "Never"

df["Days_Indoors"].apply(lambda x:days(x)).value_counts()

ee=df.groupby(["Country","Gender"])
ee["family_history"].value_counts().unstack()

w["Changes_Habits"].value_counts().unstack().plot.bar()

w["treatment"].value_counts().unstack().plot.bar()